/*
 * Copyright (c) 2025, Texas Instruments Incorporated
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of Texas Instruments Incorporated nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/*!
 * @file  ble_mux.c
 * @brief BLE HCI transport glue for the embedded TI Combined Serial MUX.
 *
 * See ble_mux.h for the architecture overview and data flow diagram.
 *
 * Assert policy:
 *   Programming errors (NULL pointers, bad return codes from stack APIs
 *   that must always succeed) are asserted.  MuxTask_sendPacket queue-full
 *   is NOT asserted here — it is already asserted inside mux_task_app.c.
 */

#include "ble_mux.h"
#include "mux_task_app.h"

#include <assert.h>
#include <stdint.h>

/* BLE SDK — HCI transport API */
#include "ti/ble/controller/hci/hci_api.h"

/*---------------------------------------------------------------------------
 * Module-private state
 *--------------------------------------------------------------------------*/

/*!
 * Registered hciControllerToHostCallbacks_t instance.
 * Held at file scope so it remains valid for the lifetime of the BLE session.
 */
static hciControllerToHostCallbacks_t gBleMuxHciCbs;

/*---------------------------------------------------------------------------
 * Forward declarations
 *--------------------------------------------------------------------------*/

static int  BleMux_hciSendCb(uint8_t *pHciPkt, uint16_t pktLen);
static void BleMux_muxRxCb(const uint8_t *buf, uint16_t len);

/*---------------------------------------------------------------------------
 * BleMux_init
 *--------------------------------------------------------------------------*/

void BleMux_init(void)
{
    uint32_t status;

    /*
     * 1. Register the HCI TX callback.
     *
     * HCI_ControllerToHostCallbacksInit() zeroes the struct; we then set
     * the single .send pointer before registering.
     *
     * After registration, any HCI event or ACL data generated by the BLE
     * controller will be delivered to BleMux_hciSendCb().
     */
    status = HCI_ControllerToHostCallbacksInit(&gBleMuxHciCbs);

    assert(status == 0U);   /* init should never fail (NULL-pointer guard) */

    (void)status;

    gBleMuxHciCbs.send = BleMux_hciSendCb;

    status = HCI_ControllerToHostRegisterCb(&gBleMuxHciCbs);

    assert(status == 0U);   /* registration must succeed */

    (void)status;

    /*
     * 2. Register the MUX RX callback for the BLE NLI channel.
     *
     * When the MUX task receives an inbound packet with NLI = MUX_NLI_BLE
     * it will call BleMux_muxRxCb() with the raw HCI payload.
     *
     * Must be called before MuxTask_create() — see mux_task_app.h contract.
     */
    MuxTask_registerRxCb((uint8_t)MUX_NLI_BLE, BleMux_muxRxCb);
}

/*---------------------------------------------------------------------------
 * BleMux_hciSendCb
 *
 * Called by the BLE HCI layer (BLE stack task context) when the controller
 * produces an HCI event or ACL data packet destined for the Linux host.
 *
 * @param pHciPkt  Raw HCI packet bytes (packet-type byte + payload).
 * @param pktLen   Total length of the HCI packet.
 *
 * @return  0 on success (matches the int return type of hciControllerToHostCallbacks_t.send).
 *--------------------------------------------------------------------------*/

static int BleMux_hciSendCb(uint8_t *pHciPkt, uint16_t pktLen)
{
    MuxErr_t err;

    assert(pHciPkt != NULL);   /* BLE stack passed NULL — programming error */
    assert(pktLen  != 0U);     /* zero-length HCI packet — should not happen */

    if (pHciPkt == NULL || pktLen == 0U)
    {
        return -1;
    }

    /*
     * Enqueue for MUX transmission.  MuxTask_sendPacket() copies the bytes
     * into the queue message, so it is safe to return to the BLE stack
     * immediately afterwards.
     *
     * If the queue is full, MuxTask_sendPacket() returns MUX_ERR_QUEUE and
     * asserts internally.  We propagate the error to the BLE layer.
     */
    err = MuxTask_sendPacket((uint8_t)MUX_NLI_BLE, pHciPkt, pktLen);

    return (err == MUX_SUCCESS) ? 0 : -1;
}

/*---------------------------------------------------------------------------
 * BleMux_muxRxCb
 *
 * Called by the MUX task when an inbound packet with NLI = MUX_NLI_BLE
 * has been received from the Linux host.  The payload is a raw HCI
 * command or ACL data packet (packet-type byte + header + data).
 *
 * @param buf  Pointer to the decoded HCI payload (valid only for this call).
 * @param len  Number of bytes in the payload.
 *--------------------------------------------------------------------------*/

static void BleMux_muxRxCb(const uint8_t *buf, uint16_t len)
{
    int status;

    assert(buf != NULL);   /* MUX task passed NULL — internal logic error */
    assert(len != 0U);     /* zero-length BLE packet — should not happen  */

    if (buf == NULL || len == 0U)
    {
        return;
    }

    /*
     * Forward the raw HCI bytes to the BLE controller.
     *
     * HCI_HostToControllerSend() takes a non-const pointer but does not
     * modify the buffer contents — the cast is safe.
     */
    status = HCI_HostToControllerSend((uint8_t *)(uintptr_t)buf, len);

    assert(status == 0);   /* BLE controller rejected the packet */
    (void)status;
}
